# bash: docker network create shared-net
networks:
  shared-net:
    external: true
    name: shared-net

services:

  redis:
    image: redis:8.4.0-alpine
    command: redis-server --requirepass admin
    networks:
      - shared-net
    ports:
      - 6379:6379

#  postgres:
#    image: postgres:18.1-alpine
#    networks:
#      - shared-net
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_DB=demo
#    volumes:
#      - ~/data/postgres-data:/var/lib/postgresql/data

  mysql:
    image: mysql:9.6.0
    networks:
      - shared-net
    ports:
      - 3306:3306
    environment:
      # For testing environment only
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=mini
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ~/data/mysql/mini:/var/lib/mysql
      # Specify the directory containing the initial SQL scripts
      - ./init_mysql:/docker-entrypoint-initdb.d

  mini-app:
    image: softa/mini-app:1.0.2
    networks:
      - shared-net
    ports:
      - 80:80
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mini?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8
      - SPRING_PULSAR_CLIENT_SERVICE_URL=pulsar://broker:6650
    depends_on:
      - redis
      - mysql

#  nginx:
#    image: nginx:1.29.4-alpine
#    ports:
#      - 80:80
##    depends_on:
##      - softa
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
