debug: false
system:
  name: Mini Application
  default-language: en-US
  enable-multi-tenancy: false
  enable-insert-id: true

security:
  encryption:
    password: 12345678
    algorithm: AESEncryption
server:
  port: 80

spring:
  data:
    redis:
      root-key: mini_dev
      host: localhost
      port: 6379
      database: 0
      password: admin
      timeout: 1000
  datasource:
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: HikariPool

oss:
  type: minio
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: demo-app
  sub-dir:

rpc:
  enable: true