services:

  elasticsearch:
    image: elasticsearch:9.2.4
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - ~/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:9.2.4
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
